### ISSUE TITLE
Update StealJS to 1.x.x

### ISSUE THREAD

**Issue by m-mujica** [bit-docs/bit-docs-generate-html#11]
https://github.com/bit-docs/bit-docs-generate-html/blob/6521d98e1b1d06abd5e8d33034d2af45dbb2003b/site/default/static/package.json#L12

**Comment by justinbmeyer** [comment]
@imaustink  / @leoj3n what happened w/ this?

**Comment by leoj3n** [comment]
Check minor branch release notes. Should back out the false positive timeout changes to the tests before making a real release. Also, you wanted to do things more properly which meant moving steal dependency into nested package.json but that didn't work straight up. You mentioned this would be shower also, but more correct.
