### ISSUE TITLE
Encode html generated from Markdown backticks

### ISSUE THREAD

**Issue by m-mujica** [bit-docs/bit-docs-generate-html#12]
If I'm not wrong, the code inside backtips is for display on the page. Escaping the HTML prevents code the be executed, e.g:

```
<script src="node_modules/steal/steal.js" main="index.stache!done-autorender"></script>
```

when that html is rendered, the browser will try to download stealjs, and we probably don't want that.

I think we could extend the commonmark parser to encode the html generated out of backticks so it doesn't get executed by the browser.

thoughts @justinbmeyer @matthewp?

**Comment by matthewp** [comment]
Where is there an example of this happening now?

**Comment by m-mujica** [comment]
Go to http://donejs.com/Apis.html, look at the 404s from the browser loading steal

Source https://github.com/donejs/donejs/blob/master/docs/apis.md

**Comment by matthewp** [comment]
The raw markdown is missing backticks.

**Comment by m-mujica** [comment]
@matthewp what do you mean by that? I clicked the "raw" button and I'm able to see the backtick
s.
 
<img width="726" alt="screen shot 2017-02-10 at 13 51 26" src="https://cloud.githubusercontent.com/assets/724877/22843740/1da34be2-ef98-11e6-9f47-f8808999161f.png">

**Comment by justinbmeyer** [comment]
@m-mujica that's a different thing.

```
5. The browser downloads the page's HTML, which includes a `<script>` tag that points to [steal](#section=section_steal).  

   <script src="node_modules/steal/steal.js" main="index.stache!done-autorender"></script>
```

That should be:

```
5. The browser downloads the page's HTML, which includes a `<script>` tag that points to [steal](#section=section_steal).  

       <script src="node_modules/steal/steal.js" main="index.stache!done-autorender"></script>
```

**Comment by justinbmeyer** [comment]
each of those "`\" should just be a `
