### ISSUE TITLE
Allow linking to section of page

### ISSUE THREAD

**Issue by christopherjbaker** [bit-docs/bit-docs-generate-html#27]
I can use syntax like `[can-stache-bindings Bindings]` to link to another page, but a similar syntax to link to a section of a page would be useful. Probably something like

```markdown
[can-stache-bindings#OneWayBindingWithObjects One Way Binding With Objects]
```

**Comment by leoj3n** [comment]
- http://spec.commonmark.org/0.27/#links
- https://github.com/bit-docs/bit-docs-generate-html/blob/master/stmd.js#L388-L547
- https://github.com/bit-docs/bit-docs-generate-html/blob/631394f5ffb0a0296d9d778eeca895969c0c8ab6/build/make_default_helpers.js#L3
- https://github.com/bit-docs/bit-docs-generate-html/blob/631394f5ffb0a0296d9d778eeca895969c0c8ab6/build/make_default_helpers.js#L71-L85
- https://github.com/bit-docs/bit-docs-generate-html/blob/631394f5ffb0a0296d9d778eeca895969c0c8ab6/build/make_default_helpers.js#L359-L361
- https://github.com/bit-docs/bit-docs-generate-html/blob/631394f5ffb0a0296d9d778eeca895969c0c8ab6/build/make_default_helpers.js#L46-L48
- https://github.com/bit-docs/bit-docs-generate-html/blob/631394f5ffb0a0296d9d778eeca895969c0c8ab6/build/make_default_helpers.js#L261
